CHANGELOG.adoc, src/core.rs, tests/integration.rs
Change to also use the extension to determine the raster image format.
=> Change determination method of raster image format

justfile
=> Fix broken include directives

CHANGELOG.adoc, build.rs, doc/man/include/section-copyright.adoc, doc/man/include/section-exit-status.adoc, doc/man/include/section-reporting-bugs.adoc, doc/man/man1/qrtool-decode.1.adoc, doc/man/man1/qrtool-encode.1.adoc, doc/man/man1/qrtool-help.1.adoc, doc/man/man1/qrtool.1.adoc, justfile, src/cli.rs, src/core.rs, src/decode.rs, src/encode.rs, src/main.rs, src/metadata.rs, tests/integration.rs
Change the comment header to the format recommended by the REUSE Specification.[^1]
[^1]: https://reuse.software/spec/#comment-headers
=> Update copyright notice

CHANGELOG.adoc, Cargo.lock, Cargo.toml
=> Update version to 0.8.5

CHANGELOG.adoc, Cargo.lock, Cargo.toml, package-lock.json
=> Update version to 0.8.6

CHANGELOG.adoc, Cargo.toml
Change `codegen-units` to 1 and `panic` to "abort".
Closes #
=> Change settings for the release profile

CHANGELOG.adoc, Cargo.lock, Cargo.toml
=> Update version to 0.8.7

CHANGELOG.adoc, src/main.rs, tests/integration.rs
=> Fix exit status when input is SVG

CHANGELOG.adoc, Cargo.lock, Cargo.toml
=> Update version to 0.8.8

CHANGELOG.adoc, README.md, docs/book/modules/ROOT/pages/install.adoc
Add installation instructions via package manager.
Closes #
=> Update installation instructions in README

CHANGELOG.adoc, Cargo.lock, Cargo.toml
=> Update version to 0.8.9

CHANGELOG.adoc, Cargo.lock, Cargo.toml, src/app.rs, src/cli.rs, src/encode.rs, src/main.rs
=> Change to use `qrcode` crate

CHANGELOG.adoc, Cargo.lock, Cargo.toml
=> Update version to 0.9.0

CHANGELOG.adoc, Cargo.lock, Cargo.toml, tests/integration.rs
=> Update version to 0.10.0

CHANGELOG.adoc, Cargo.lock, Cargo.toml, package-lock.json, package.json
=> Update version to 0.10.1

CHANGELOG.adoc, Cargo.lock, Cargo.toml
=> Update version to 0.10.2

src/main.rs
=> Change to use `matches!`

tests/data/decode/decode.txt, tests/integration.rs
=> Add I/O tests

tests/integration.rs
=> Add tests for `--generate-completion`

CHANGELOG.adoc, Cargo.lock, Cargo.toml, docs/book/modules/ROOT/nav.adoc, docs/book/modules/ROOT/pages/contributing.adoc, package-lock.json
=> Update version to 0.10.3

CHANGELOG.adoc, docs/man/man1/qrtool-decode.1.adoc, docs/man/man1/qrtool-encode.1.adoc, docs/man/man1/qrtool.1.adoc
Add description about behavior of `-h`, `--help` and `--version`.
Closes #
=> Update man pages

.github/workflows/CD.yaml, CHANGELOG.adoc, Cargo.lock, Cargo.toml
=> Update version to 0.10.4

CHANGELOG.adoc, Cargo.lock, Cargo.toml, package-lock.json, src/decode.rs
=> Update version to 0.10.5

src/decode.rs, src/encode.rs
=> Change to use `RgbaImage` directly

CHANGELOG.adoc, Cargo.lock, Cargo.toml, package-lock.json
=> Update version to 0.10.6

.github/workflows/CD.yaml, CHANGELOG.adoc, Cargo.lock, Cargo.toml
=> Update version to 0.10.7

CHANGELOG.adoc, Cargo.lock, Cargo.toml, package-lock.json
=> Update version to 0.10.8

CHANGELOG.adoc, Cargo.lock, Cargo.toml
=> Update version to 0.10.9

BUILD.adoc, CHANGELOG.adoc, Cargo.lock, Cargo.toml, README.md, build.rs, docs/book/modules/ROOT/pages/usage.adoc, docs/man/man1/qrtool-decode.1.adoc, src/cli.rs, tests/integration.rs
=> Change input image formats to optional

.github/workflows/CD.yaml, CHANGELOG.adoc, Cargo.lock, Cargo.toml, package-lock.json
=> Update version to 0.10.10

src/cli.rs
=> Fix clippy error

CHANGELOG.adoc, Cargo.lock, Cargo.toml, package-lock.json
=> Update version to 0.10.11

BUILD.adoc, CHANGELOG.adoc, Cargo.lock, Cargo.toml, README.md, build.rs, docs/book/modules/ROOT/pages/usage.adoc, docs/man/man1/qrtool-encode.1.adoc, src/app.rs, src/cli.rs, tests/encode.rs
=> Add options to optimize output PNG image

.github/workflows/CD.yaml, CHANGELOG.adoc, Cargo.lock, Cargo.toml, package-lock.json
=> Update version to 0.10.12

CHANGELOG.adoc, Cargo.lock, Cargo.toml
=> Update version to 0.10.13

CHANGELOG.adoc, docs/man/man1/qrtool-encode.1.adoc, src/app.rs, src/cli.rs, tests/encode.rs
=> Change `--zopfli` to allow it to take a value

CHANGELOG.adoc, Cargo.lock, Cargo.toml
=> Update version to 0.11.0

.github/workflows/CD.yaml, CHANGELOG.adoc, Cargo.lock, Cargo.toml, package-lock.json
=> chore(release): Update version to 0.11.1

CHANGELOG.adoc
=> docs: Fix CHANGELOG

CHANGELOG.adoc, Cargo.lock, Cargo.toml
=> chore(release): Update version to 0.11.2

README.md, docs/book/modules/ROOT/pages/usage.adoc
=> docs: Update README

CHANGELOG.adoc, README.md, docs/book/modules/ROOT/pages/usage.adoc, src/app.rs, src/cli.rs, src/decode.rs, tests/decode.rs
Change SVG image to predict file contents instead of filename extension.
Closes #
=> feat:(decode): Improve file format prediction

Cargo.lock, Cargo.toml, src/app.rs
=> chore: Use `is-svg` crate

CHANGELOG.adoc, Cargo.lock, Cargo.toml, package-lock.json
=> chore(release): Update version to 0.11.3

docs/man/man1/qrtool-decode.1.adoc, docs/man/man1/qrtool-encode.1.adoc, docs/man/man1/qrtool-help.1.adoc, docs/man/man1/qrtool.1.adoc
=> docs: Update man pages

CHANGELOG.adoc, Cargo.lock, Cargo.toml, package-lock.json
=> chore(release): Update version to 0.11.4

README.md, docs/book/modules/ROOT/nav.adoc, docs/book/modules/ROOT/pages/repository.adoc
=> docs: Add information about repositories

README.md, docs/book/modules/ROOT/pages/usage.adoc, docs/man/man1/qrtool-encode.1.adoc, src/cli.rs
=> docs: Update description about color conversion

CHANGELOG.adoc, Cargo.lock, Cargo.toml, package-lock.json
=> chore(release): Update version to 0.11.5

src/app.rs
rqrr doesn't appear to work if the background is darker than
the foreground. So we try with an inverted image if decoding
fails or no content is returned.
A simple test-case:
``` bash
for n in {0..9} {a..f}; do
echo $n
qrtool e -l h --foreground=${n}0${n}0${n}0 --background=808080 < <(echo 'https://github.com/sorairolake/qrtool') | qrtool d
done
```
Before
```
0
https://github.com/sorairolake/qrtool
1
https://github.com/sorairolake/qrtool
2
https://github.com/sorairolake/qrtool
3
https://github.com/sorairolake/qrtool
4
https://github.com/sorairolake/qrtool
5
https://github.com/sorairolake/qrtool
6
https://github.com/sorairolake/qrtool
7
8
9
a
b
c
d
e
f
```
After
```
0
https://github.com/sorairolake/qrtool
1
https://github.com/sorairolake/qrtool
2
https://github.com/sorairolake/qrtool
3 …
```
=> feat: fall-back to decoding an inverted image

AUTHORS.adoc, CHANGELOG.adoc, src/app.rs
=> docs: Update `CHANGELOG.adoc`

CHANGELOG.adoc, Cargo.lock, Cargo.toml, package-lock.json
=> chore(release): Update version to 0.11.6

src/cli.rs, tests/encode.rs
=> chore: Remove `allow`

.bumpversion.toml, CHANGELOG.adoc, build.rs, docs/man/man1/qrtool-decode.1.adoc, docs/man/man1/qrtool-encode.1.adoc, docs/man/man1/qrtool-help.1.adoc, docs/man/man1/qrtool.1.adoc, justfile
=> docs: Reduce `ifdef` from man pages

.bumpversion.toml, CHANGELOG.adoc, Cargo.lock, Cargo.toml, docs/man/man1/qrtool-decode.1.adoc, docs/man/man1/qrtool-encode.1.adoc, docs/man/man1/qrtool-help.1.adoc, docs/man/man1/qrtool.1.adoc, package-lock.json
=> chore(release): Update version to 0.11.7

README.md, docs/book/modules/ROOT/pages/index.adoc
=> chore: Add REUSE compliance badge

.bumpversion.toml, CHANGELOG.adoc, Cargo.lock, Cargo.toml, docs/man/man1/qrtool-decode.1.adoc, docs/man/man1/qrtool-encode.1.adoc, docs/man/man1/qrtool-help.1.adoc, docs/man/man1/qrtool.1.adoc, package-lock.json
=> chore(release): Update version to 0.11.8

CHANGELOG.adoc, README.md, docs/book/modules/ROOT/nav.adoc, docs/book/modules/ROOT/pages/man/man1/qrtool-completion.1.adoc, docs/book/modules/ROOT/pages/usage.adoc, docs/man/man1/qrtool-completion.1.adoc, docs/man/man1/qrtool-decode.1.adoc, docs/man/man1/qrtool-encode.1.adoc, docs/man/man1/qrtool.1.adoc, src/app.rs, src/cli.rs, tests/assets/completion-after-long-help.md, tests/assets/completion-after-long-help.md.license, tests/integration.rs
=> chore: Replace `--generate-completion` with `completion` subcommand

src/cli.rs
=> chore(completion): Change shell name to be case insensitive

src/cli.rs, tests/completion.rs, tests/integration.rs
=> test: Add test for when subcommand is not provided

CHANGELOG.adoc, docs/man/man1/qrtool-decode.1.adoc, docs/man/man1/qrtool-encode.1.adoc, docs/man/man1/qrtool.1.adoc, src/cli.rs, tests/assets/after-long-help.md, tests/assets/after-long-help.md.license, tests/assets/completion-after-long-help.md, tests/assets/completion-after-long-help.md.license, tests/assets/decode-after-long-help.md, tests/assets/decode-after-long-help.md.license, tests/assets/encode-after-long-help.md, tests/assets/encode-after-long-help.md.license, tests/assets/long-version.md, tests/assets/long-version.md.license, tests/completion.rs, tests/decode.rs, tests/encode.rs, tests/integration.rs
=> chore: Simplify `--help` and `--version` output

src/cli.rs
=> chore: Update description for `--help`

tests/completion.rs
=> test: Add tests for infer subcommand names

.bumpversion.toml, CHANGELOG.adoc, Cargo.lock, Cargo.toml, docs/man/man1/qrtool-completion.1.adoc, docs/man/man1/qrtool-decode.1.adoc, docs/man/man1/qrtool-encode.1.adoc, docs/man/man1/qrtool.1.adoc, package-lock.json
=> chore(release): Update version to 0.12.1

LICENSE-MIT, LICENSES/MIT.txt, README.md, docs/book/modules/ROOT/pages/license.adoc, docs/book/supplemental-ui/partials/footer-content.hbs, docs/man/man1/include/section-copyright.adoc
=> chore: Update copyright notice

.github/workflows/CI.yaml, .github/workflows/just.yaml, .github/workflows/tombi.yaml, docs/book/supplemental-ui/partials/footer-content.hbs, docs/book/supplemental-ui/partials/header-content.hbs
=> ci: Check if files are formatted

.github/workflows/CD.yaml, .gitignore, .goreleaser.yaml, CHANGELOG.adoc
=> ci: Change to use GoReleaser
